import CartItemMdl from "@/models/products/card-item";
import DiscountMdl from "@/models/products/discount";
import { InventoryMdl } from "@/models/products/inventory";
import BrandMdl from "@/models/users/brand";
import { DateTime } from "next-auth/providers/kakao";

const brands: BrandMdl[] = [
    { id: "b1", name: "Thương hiệu A", avatarUrl: "/images/product-detail.png" },
    { id: "b2", name: "Thương hiệu B", avatarUrl: "/images/product-detail.png" },
    { id: "b3", name: "Thương hiệu C", avatarUrl: "/images/product-detail.png" },
    { id: "b4", name: "Thương hiệu D", avatarUrl: "/images/product-detail.png" },
    { id: "b5", name: "Thương hiệu E", avatarUrl: "/images/product-detail.png" },
];

const discounts: DiscountMdl[] = [
    {
        id: "d1",
        name: "Giảm giá 10%",
        type: "percentage",
        discountCode: "SAVE10",
        discountPrice: 0,
        discountPercent: 10,
        maxDiscountPrice: 50,
        minOrderPrice: 100,
        discountCons: ["Không áp dụng cho sản phẩm X"],
        expiredDate: new Date("2024-12-31") as unknown as DateTime,
        description: "Giảm 10% cho đơn hàng từ 100.000 VNĐ trở lên.",
    },
    {
        id: "d2",
        name: "Giảm giá 20.000 VNĐ",
        type: "fixed",
        discountCode: "SAVE20000",
        discountPrice: 20000,
        discountPercent: 0,
        maxDiscountPrice: 20000,
        minOrderPrice: 200,
        expiredDate: new Date("2024-11-30") as unknown as DateTime,
        description: "Giảm 20.000 VNĐ cho đơn hàng từ 200.000 VNĐ trở lên.",
    },
];

const inventories: InventoryMdl[] = [
    {
        id: "i1",
        quantitySold: 150,
        quantityAvailable: 50,
        variantName: "Màu sắc",
        variantValue: "Đỏ",
        price: 200000,
    },
    {
        id: "i2",
        quantitySold: 200,
        quantityAvailable: 30,
        variantName: "Kích thước",
        variantValue: "L",
        price: 250000,
    },
    {
        id: "i3",
        quantitySold: 100,
        quantityAvailable: 80,
        variantName: "Màu sắc",
        variantValue: "Xanh",
        price: 300000,
    },
];

export const cartItems: CartItemMdl[] = [
    {
        id: "c1",
        name: "Nước mắm Vịnh Vân Phong (Chai du lịch mini)",
        price: 100000,
        imageUrl: "/images/product-detail.png",
        rating: 4.5,
        quantitySold: 200,
        inventories: [inventories[0], inventories[1]],
        discount: discounts[0],
        brand: brands[0],
    },
    {
        id: "c2",
        name: "Muối Lá É Dì Hưng",
        price: 200000,
        imageUrl: "/images/product-detail.png",
        rating: 4.0,
        quantitySold: 150,
        inventories: [inventories[1]],
        brand: brands[1],
    },
    {
        id: "c3",
        name: "Kem Dưỡng Da Ban Đêm C",
        price: 300000,
        imageUrl: "/images/product-detail.png",
        inventories: [inventories[2]],
        discount: discounts[1],
        brand: brands[2],
    },
    {
        id: "c4",
        name: "Gel Rửa Mặt D",
        price: 400000,
        imageUrl: "/images/product-detail.png",
        inventories: [],
        brand: brands[3],
    },
    {
        id: "c5",
        name: "Nước Rửa Chén Bồ Hòn Chai 500 ml",
        price: 500000,
        imageUrl: "/images/product-detail.png",
        inventories: [inventories[0]],
        discount: discounts[0],
        brand: brands[4],
    },
    {
        id: "c6",
        name: "Sữa Rửa Mặt F",
        price: 600000,
        imageUrl: "/images/product-detail.png",
        rating: 4.2,
        quantitySold: 180,
        inventories: [inventories[1], inventories[2]],
        discount: discounts[1],
        brand: brands[0],
    },
    {
        id: "c7",
        name: "Kem Chống Nắng G",
        price: 700000,
        imageUrl: "/images/product-detail.png",
        rating: 4.8,
        quantitySold: 210,
        inventories: [inventories[0]],
        brand: brands[1],
    },
    {
        id: "c8",
        name: "Mặt Nạ Dưỡng Ẩm H",
        price: 800000,
        imageUrl: "/images/product-detail.png",
        rating: 3.9,
        quantitySold: 90,
        inventories: [],
        brand: brands[2],
    },
    {
        id: "c9",
        name: "Toner Làm Sạch I",
        price: 900000,
        imageUrl: "/images/product-detail.png",
        rating: 4.0,
        quantitySold: 120,
        inventories: [inventories[1]],
        discount: discounts[0],
        brand: brands[3],
    },
    {
        id: "c10",
        name: "Dầu Tẩy Trang J",
        price: 1000000,
        imageUrl: "/images/product-detail.png",
        rating: 4.7,
        quantitySold: 175,
        inventories: [inventories[0], inventories[2]],
        brand: brands[4],
    },
    {
        id: "c11",
        name: "Kem Nền K",
        price: 1100000,
        imageUrl: "/images/product-detail.png",
        rating: 4.3,
        quantitySold: 130,
        inventories: [inventories[1]],
        discount: discounts[1],
        brand: brands[0],
    },
    {
        id: "c12",
        name: "Phấn Nền L",
        price: 1200000,
        imageUrl: "/images/product-detail.png",
        rating: 4.6,
        quantitySold: 165,
        inventories: [inventories[2]],
        brand: brands[1],
    },
    {
        id: "c13",
        name: "Son Môi M",
        price: 1300000,
        imageUrl: "/images/product-detail.png",
        rating: 3.8,
        quantitySold: 140,
        inventories: [],
        brand: brands[2],
    },
    {
        id: "c14",
        name: "Nước Tẩy Trang N",
        price: 1400000,
        imageUrl: "/images/product-detail.png",
        rating: 4.1,
        quantitySold: 155,
        inventories: [inventories[0]],
        discount: discounts[0],
        brand: brands[3],
    },
    {
        id: "c15",
        name: "Kem Chống Lão Hóa O",
        price: 1500000,
        imageUrl: "/images/product-detail.png",
        rating: 4.4,
        quantitySold: 110,
        inventories: [inventories[1], inventories[2]],
        brand: brands[4],
    },
    {
        id: "c16",
        name: "Mặt Nạ Ngủ P",
        price: 1600000,
        imageUrl: "/images/product-detail.png",
        rating: 4.9,
        quantitySold: 200,
        inventories: [inventories[0]],
        discount: discounts[1],
        brand: brands[0],
    },
    {
        id: "c17",
        name: "Tinh Chất Làm Sáng Q",
        price: 1700000,
        imageUrl: "/images/product-detail.png",
        rating: 4.3,
        quantitySold: 190,
        inventories: [inventories[1]],
        brand: brands[1],
      },
      {
        id: "c18",
        name: "Mặt Nạ Dưỡng Sáng R",
        price: 1800000,
        imageUrl: "/images/product-detail.png",
        rating: 4.5,
        quantitySold: 220,
        inventories: [inventories[2]],
        discount: discounts[1],
        brand: brands[2],
      },
      {
        id: "c19",
        name: "Kem Làm Dịu Da S",
        price: 1900000,
        imageUrl: "/images/product-detail.png",
        rating: 4.2,
        quantitySold: 170,
        inventories: [inventories[0], inventories[1]],
        brand: brands[3],
      },
      {
        id: "c20",
        name: "Toner Dịu Nhẹ T",
        price: 2000000,
        imageUrl: "/images/product-detail.png",
        rating: 4.7,
        quantitySold: 230,
        inventories: [inventories[1], inventories[2]],
        discount: discounts[0],
        brand: brands[4],
      },
];


